/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author pollo
 */
public class pnlModoJuego extends javax.swing.JPanel {

    /**
     * Creates new form pnlModoJuego
     */
    public pnlModoJuego() {
        initComponents();
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public JPanel getPnlCartonLleno() {
        return pnlCartonLleno;
    }

    public JPanel getPnlCartonNormal() {
        return pnlCartonNormal;
    }

    public JPanel getPnlCuatroEsquinas() {
        return pnlCuatroEsquinas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCuatroEsquinas = new javax.swing.JPanel();
        lblCuatroEsquinas = new javax.swing.JLabel();
        pnlCartonLleno = new javax.swing.JPanel();
        lblCartonLleno = new javax.swing.JLabel();
        pnlCartonNormal = new javax.swing.JPanel();
        lblCartonNormal = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        pnlCuatroEsquinas.setBackground(new java.awt.Color(255, 51, 51));
        pnlCuatroEsquinas.setPreferredSize(new java.awt.Dimension(140, 140));

        lblCuatroEsquinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuatroEsquinas.setText("Juego Cuatro esquinas");

        javax.swing.GroupLayout pnlCuatroEsquinasLayout = new javax.swing.GroupLayout(pnlCuatroEsquinas);
        pnlCuatroEsquinas.setLayout(pnlCuatroEsquinasLayout);
        pnlCuatroEsquinasLayout.setHorizontalGroup(
            pnlCuatroEsquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCuatroEsquinas, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlCuatroEsquinasLayout.setVerticalGroup(
            pnlCuatroEsquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuatroEsquinasLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblCuatroEsquinas)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pnlCartonLleno.setBackground(new java.awt.Color(153, 153, 255));
        pnlCartonLleno.setPreferredSize(new java.awt.Dimension(140, 140));

        lblCartonLleno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCartonLleno.setText("Juego Cartón Lleno");

        javax.swing.GroupLayout pnlCartonLlenoLayout = new javax.swing.GroupLayout(pnlCartonLleno);
        pnlCartonLleno.setLayout(pnlCartonLlenoLayout);
        pnlCartonLlenoLayout.setHorizontalGroup(
            pnlCartonLlenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCartonLleno, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlCartonLlenoLayout.setVerticalGroup(
            pnlCartonLlenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartonLlenoLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(lblCartonLleno)
                .addGap(60, 60, 60))
        );

        pnlCartonNormal.setBackground(new java.awt.Color(102, 255, 51));

        lblCartonNormal.setText("Juego Normal");

        javax.swing.GroupLayout pnlCartonNormalLayout = new javax.swing.GroupLayout(pnlCartonNormal);
        pnlCartonNormal.setLayout(pnlCartonNormalLayout);
        pnlCartonNormalLayout.setHorizontalGroup(
            pnlCartonNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartonNormalLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lblCartonNormal)
                .addGap(31, 31, 31))
        );
        pnlCartonNormalLayout.setVerticalGroup(
            pnlCartonNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartonNormalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblCartonNormal)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlCartonNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlCuatroEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(pnlCartonLleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(732, Short.MAX_VALUE)
                    .addComponent(btnVolver)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCartonLleno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCuatroEsquinas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlCartonNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(445, Short.MAX_VALUE)
                    .addComponent(btnVolver)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCartonLleno;
    private javax.swing.JLabel lblCartonNormal;
    private javax.swing.JLabel lblCuatroEsquinas;
    private javax.swing.JPanel pnlCartonLleno;
    private javax.swing.JPanel pnlCartonNormal;
    private javax.swing.JPanel pnlCuatroEsquinas;
    // End of variables declaration//GEN-END:variables
}
