/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author CristianG
 */
public class pnlTipoJuego extends javax.swing.JPanel {

    /**
     * Creates new form pnlTipoJuego
     */
    public pnlTipoJuego() {
        initComponents();
    }
    
    public JPanel getPnlManual() {
        return pnlManual;
    }
    
    public JPanel getPnlAutomatico() {
        return pnlAutomatico;
    }
    
    public JButton getBtnVolver() {
        return btnVolver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAutomatico = new javax.swing.JPanel();
        lblManual = new javax.swing.JLabel();
        pnlManual = new javax.swing.JPanel();
        lblAutomatico = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        pnlAutomatico.setBackground(new java.awt.Color(51, 51, 255));
        pnlAutomatico.setPreferredSize(new java.awt.Dimension(140, 140));

        lblManual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManual.setText("Manual");

        javax.swing.GroupLayout pnlAutomaticoLayout = new javax.swing.GroupLayout(pnlAutomatico);
        pnlAutomatico.setLayout(pnlAutomaticoLayout);
        pnlAutomaticoLayout.setHorizontalGroup(
            pnlAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutomaticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManual, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAutomaticoLayout.setVerticalGroup(
            pnlAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutomaticoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblManual)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pnlManual.setBackground(new java.awt.Color(51, 51, 255));
        pnlManual.setPreferredSize(new java.awt.Dimension(140, 140));

        lblAutomatico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutomatico.setText("Automatico");

        javax.swing.GroupLayout pnlManualLayout = new javax.swing.GroupLayout(pnlManual);
        pnlManual.setLayout(pnlManualLayout);
        pnlManualLayout.setHorizontalGroup(
            pnlManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAutomatico, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlManualLayout.setVerticalGroup(
            pnlManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManualLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblAutomatico)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnlManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(pnlAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblAutomatico;
    private javax.swing.JLabel lblManual;
    private javax.swing.JPanel pnlAutomatico;
    private javax.swing.JPanel pnlManual;
    // End of variables declaration//GEN-END:variables
}
